# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: def123e610fde8f7c5312a61bf8531d536e0f5b0553345f75a123d910e93786977f74f78cd0e7e7b040b39f12963b3a1c646fc8755ab14366239af89405956d0

test:
  secret_key_base: 2e5d429be618e4913ed1b5c58d54111b5e895b77e0bf3b94f2e19aa191ab389bec9444229fa46a3f241cf593c3e8c7c7114eab2ca9cbc36e8f5bd0c039b3ce56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
